# spring
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/MS_SKELETON
    username: MS_SKELETON
    password: MS_SKELETON
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  cloud:
    function:
      definition: processExternalOrderEvent
    stream:
      bindings:
        processExternalOrderEvent-in-0:
          destination: external-order-event-topic
          group: ${spring.application.name}
        order-event-topic-out-0:
          destination: order-event-topic
          group: ${spring.application.name}
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: false
    openfeign:
      okhttp:
        enabled: true

# application configs
app:
  ms-skeleton:
    orderCreationEnabled: true
    userServiceApiVersion: v1
    feign:
      url: http://localhost:${server.port:8080}
    test-property: value
  ms-user:
    feign:
      url: http://localhost:${wiremock.server.port:8080}
  seaweedfs:
    host: "localhost"
    http-port: 8888
    grpc-port: 18888
    root-directory: "/ms-skeleton"
